name: Run CI on branch builds

on:
  push:
    branches-ignore:
      - master

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Jest unit tests
        if: success()
        run: yarn test --ci
      - name: Cypress integration tests
        run: |
          yarn start & wait-on http://localhost:3000
          yarn run cypress run
